### ISSUE TITLE
ADC Read Speed and SPI Clock

### ISSUE THREAD

**Issue by bhclowers** [abelectronicsuk/ABElectronics_Python3_Libraries#5]
Based upon the product webpage the maximum stated ADC clock speed under python is 12,000 samples per second.  Even when changing the value of the spi clock in the ABE_ADCDACPi.py the speed seems to be fairly static at around 200 us.  I'm using raspberry pi w with Jessie.  Can anyone describe how to enable similar speeds for the ADC module?

Original: 
    spiADC.max_speed_hz = (900000)
Changed to:
    spiADC.max_speed_hz = (25000000)

Code used for the test:

from ABE_ADCDACPi import ADCDACPi
import time
import numpy as N
import datetime
adcdac = ADCDACPi()  # create an instance of ADCDACPi

adcdac.set_adc_refvoltage(3.3)

numPnts = 1000
a = N.zeros(numPnts)
counter = 1
starttime = datetime.datetime.now()
print(starttime)
while (counter < numPnts):
    # read the voltage from channel 1
    a[counter] = adcdac.read_adc_raw(1,0)
    counter+=1
endtime = datetime.datetime.now()

print(endtime - starttime)
print(endtime)

**Comment by briandorey** [comment]
The python speed listed on the ADC DAC page was based on a test using python 2 on a Raspberry Pi 2 which was the current model at the time of the ADCDAC Pi Zero launch.  As the Pi W has an older processor which runs at a slower clock rate the maximum sample rate will be slower.  The number of processes running will also have an impact on the maximum sample rate as linux will try to delegate time to each process.

To get the maximum performance with python I would recommend using python 2 instead of python 3 as I have found it to be as much as 20% faster when reading from the ADC.  I have uploaded new versions of the demo-speed.py to both the Python 2 and Python 3 versions of our ADC DAC Pi library so you can compare the speed difference between the two versions of the library.

**Comment by bhclowers** [comment]
Brian,

Thanks for the update.  I'm hoping to carve out some time to investigate
this tonight.  I appreciate the assistance.

Regards,

Brian
